### ISSUE TITLE
Ninja just spam shadows and if you remove utsusemi from the list you can't put it back unless you delete the job setting under data and reload trust.

### ISSUE THREAD

**Issue by Makiavelli2** [cyritegamestudios/trust#121]

**Comment by cyrite** [comment]
@Makiavelli2 Is this with Utsusemi: Ichi or San? Because of the way copy image buffs are represented the logic is currently to recast if you don't have exactly 3 shadows (default for Ni).

For re-adding Utsusemi as a buff, are you able to do it in the Settings > Buffs > Self > Add menu?

![image](https://github.com/cyritegamestudios/trust/assets/123847593/269973ea-3e5a-4bd6-8f0d-39b6f24ffeae)

**Comment by Makiavelli2** [comment]
No this is all i see 
![Screenshot 2024-06-26 221456](https://github.com/cyritegamestudios/trust/assets/153099533/6a4b6eb9-10cc-44ae-a382-9db9e7782053)

**Comment by cyrite** [comment]
Huh, that is super odd. I'm sure this isn't the problem but can you check a few things:

1. Does that character know Utsusemi: Ichi, Ni and/or San?
2. Are there any errors in the Windower console?

Also have you tried upgrading to the [latest version](https://github.com/cyritegamestudios/trust/releases/) of Trust? If you are using Git, you can also try what's on [main](https://github.com/cyritegamestudios/trust).

**Comment by cyrite** [comment]
I'm reasonably certain this is fixed on [main](https://github.com/cyritegamestudios/trust). Once I get a bit more testing on that I'll push out a new release.

**Comment by Makiavelli2** [comment]
Yea I downloaded the latest and now it works 😀🤘
