### ISSUE TITLE
Self Targets When Assisting Others

### ISSUE THREAD

**Issue by berkaester** [cyritegamestudios/trust#131]
Running into an issue when putting the setting on auto assist or assist in general. It will work well for a bit and then it will start to self target when auto target mode options are set to "Party" or "Same". It seems to happen more often than not when the bot is healed or something once the fight is over, it doesn't clear whatever last targeted it and then when it tries to assist it self targets... Of course this seems to happen when I am not really paying attention to it and go afk. 

Bloody great addon though :D

**Comment by cyrite** [comment]
Thank you! As for your issue, assisting is not possible when `AutoTargetMode` or `AutoPullMode` are set to anything but `Off`. This is because they both determine which mobs the Trust targets and would conflict. You don't need to set `AutoTargetMode` in order for your alts to engage the mob you are fighting, just assist! I will add some code to automatically disable the assist when changing the values of these modes.

**Comment by cyrite** [comment]
Should be fixed in the most recent release. It will disengage and re-engage when it happens. Let me know if it still doesn't work!
