### ISSUE TITLE
Pull Mobs Not Clearing 

### ISSUE THREAD

**Issue by berkaester** [cyritegamestudios/trust#132]
Also ran into another issue whereby I can't clear the list of mobs on the pull list. It just doesn't do anything, however, this is on a PLD profile so not sure has anything to do with it as I know that job may still have some bugs to work out? No matter how many times I click and press confirm or clear the list remains the same lol

**Comment by berkaester** [comment]
just updated files to latest version and still can't select mobs to target or clear the list of mobs to target in pull mode.

**Comment by cyrite** [comment]
@berkaester can you start a thread on the [Cyrite Game Studios Discord](https://discord.gg/CfPxDy759J) so we can debug? I just checked on Paladin and it seems to work fine for me so I'm guessing the issue is non-backwards compatible settings and/or you may have manually edited your settings. Also this may not be obvious, but you actually have to select the name of the mob first (selected means the name is in yellow, **not** pink).

![image](https://github.com/user-attachments/assets/1965065e-1b6e-4f9c-8657-803a7e1a6df1)

**Comment by berkaester** [comment]
Will do. Thanks for replying. 

Also this may not be obvious, but you actually have to select the name of the mob first (selected means the name is in yellow, not pink). The same goes for removing. I would suggest using the keyboard instead of the mouse if that's not already what you are doing. --- I have tried this :D 

I think maybe it non-backwards compatible settings and/or you may have manually edited your settings.

**Comment by cyrite** [comment]
If you don't mind losing your data, try deleting `addons/trust/settings.xml` and running `// lua r trust`.
